# 确保查看 http://goreleaser.com 上的文档
version: 2
builds:
  - ldflags:
      - -w -s
      - -X github.com/purpose168/edgevpn/internal.Version={{.Tag}}
      - -X github.com/purpose168/edgevpn/internal.Commit={{.Commit}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm
      - 386
      - arm64
source:
  enabled: true
  name_template: '{{ .ProjectName }}-{{ .Tag }}-source'
archives:
  # 默认模板使用下划线而不是 -
  - name_template: >-
      {{ .ProjectName }}-{{ .Tag }}-
      {{- if eq .Os "freebsd" }}FreeBSD
      {{- else }}{{- title .Os }}{{end}}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{end}}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
checksum:
  name_template: '{{ .ProjectName }}-{{ .Tag }}-checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^Merge pull request'
